#!/usr/bin/env ruby

require "nkf"
require "hiki2gh"

if ARGV.size < 2
  STDERR.puts("Usage: hiki2md <source dir> <destination dir>")
  exit(1)
end


farm = Hiki2gh::HikiFarm.new(ARGV[0])
farm.export(ARGV[1])


